#!/bin/sh

# This file mimics the environment setup done by
# C:\MSVC9.0\Common7\Tools\vsvars32.bat

# Change these to match your installation paths
VCROOT="c:\MSVC9.0"
VCDIR="$VCROOT\VC"
COMDIR="$VCROOT\Common7"
WSDKDIR="c:\Program Files\Microsoft SDKs\Windows\v6.0A"
DOTNET="c:\WINDOWS\Microsoft.NET\Framework"

# Lib and INCLUDE should be Windows'ish
# Note that semicolon (;) is used to separate Windows style paths but
# colon (:) to separate Cygwin ditto!

INCLUDE="$VCDIR\include;$WSDKDIR\include"
LIB="$VCDIR\lib;$WSDKDIR\lib"
LIBPATH="$DOTNET\v3.5;$DOTNET\v2.0.50727;$VCDIR\lib"

# The PATH variable should be Cygwin'ish
# BUT we'll leave the PATH sanitation to the
# eval `./otp_build env_win32`
# build step.
PATH="$WSDKDIR\bin:$PATH"
PATH="$COMDIR\IDE:$PATH"
PATH="$VCDIR\bin:$PATH"
PATH="$COMDIR\Tools:$PATH"
PATH="$COMDIR\Tools/bin:$PATH"
PATH="$DOTNET\v3.5:$DOTNET\v2.0.50727:$PATH"
PATH="$VCDIR\vcPackages:$PATH"

export INCLUDE LIB LIBPATH PATH

echo "Say 'exit' to leave the VC2008 shell and restore Cygwin environment."
/usr/bin/bash --rcfile ~/.vcvars9rc
