#!/bin/sh

# This file mimics the environment setup done by
# C:\MSVC9.0\Common7\Tools\vsvars32.bat

# Change these to match your installation paths
WIN_VCROOT="c:/MSVC9.0"
WIN_VCDIR="$WIN_VCROOT/VC"
WIN_WSDKDIR="c:\\Program Files\\Microsoft SDKs\\Windows\\v6.0A"
WIN_DOTNET="c:\\WINDOWS\\Microsoft.NET\\Framework"

# Lib and INCLUDE should be Windows'ish
# Note that semicolon (;) is used to separate Windows style paths but
# colon (:) to separate Cygwin ditto!

INCLUDE="$WIN_VCDIR\\include;$WIN_WSDKDIR\\include"
LIB="$WIN_VCDIR\\lib;$WIN_WSDKDIR\\lib"
LIBPATH="$WIN_DOTNET\\v3.5;$WIN_DOTNET\\v2.0.50727;$WIN_VCDIR\\lib"

# The PATH variable should be Cygwin'ish
VCROOT=`cygpath "$WIN_VCROOT"`
VCDIR="$VCROOT/VC"
COMDIR="$VCROOT/Common7"
WSDKDIR=`cygpath "$WIN_WSDKDIR"`
DOTNET=`cygpath "$WIN_DOTNET"`

PATH="$WSDKDIR/bin:$PATH"
PATH="$COMDIR/IDE:$PATH"
PATH="$VCDIR/bin:$PATH"
PATH="$COMDIR/Tools:$PATH"
PATH="$COMDIR/Tools/bin:$PATH"
PATH="$DOTNET/v3.5:$DOTNET/v2.0.50727:$PATH"
PATH="$VCDIR/vcPackages:$PATH"

export INCLUDE LIB LIBPATH PATH

echo "Say 'exit' to leave the VC2008 shell and restore Cygwin environment."
/usr/bin/bash --rcfile ~/.vcvars9rc
